trigger: none

stages:

  - stage: Build
    displayName: BUILD
    jobs:
      - template: build/build.yml

  - stage: DeployApi
    displayName: DeployApi
    jobs:
      - template: deploy/api.deploy.yml
      
  - stage: DeployApp
    displayName: DeployApp
    jobs:
      - template: deploy/app.deploy.yml